# Generated by Django 3.2.9 on 2021-12-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
