# Generated by Django 3.2.9 on 2021-12-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markito', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='code',
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.URLField(),
        ),
    ]
