# Generated by Django 3.2.9 on 2021-12-07 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markito', '0002_auto_20211207_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='user',
        ),
    ]
