# Generated by Django 3.2.9 on 2021-12-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markito', '0003_remove_products_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='costs',
        ),
    ]
